#+TITLE: paper-reading

List of papers we cover during our weekly paper reading session. At the moment,
only list the citations with pdf links, if possible, in reverse chronological
order. For past links/notes, check out the (private) wiki.

BibTeX entries can be found in [[file:./library.bib][library.bib]] file.

** 1 June, 2019
- Russo, D. J., Van Roy, B., Kazerouni, A., Osband, I., Wen, Z., & others, , A
  tutorial on thompson sampling, Foundations and Trends{\textregistered} in
  Machine Learning, 11(1), 1–96 (2018). (cite:russo2018tutorial)

** 18 May, 2019
- Mintz, M., Bills, S., Snow, R., & Jurafsky, D., [[https://web.stanford.edu/~jurafsky/mintz.pdf][Distant supervision for
  relation extraction without labeled data]], In , Proceedings of the Joint
  Conference of the 47th Annual Meeting of the ACL and the 4th International
  Joint Conference on Natural Language Processing of the AFNLP: Volume 2-Volume
  2 (pp. 1003–1011) (2009). (cite:mintz2009distant)

- Beygelzimer, A., Daum\'e, Hal, Langford, J., & Mineiro, P., [[https://arxiv.org/abs/1502.02704][Learning
  reductions that really work]], Proceedings of the IEEE, 104(1), 136–147 (2016).
  (cite:beygelzimer2016learning)

- Gravano, A., Jansche, M., & Bacchiani, M., [[https://storage.googleapis.com/pub-tools-public-publication-data/pdf/34562.pdf][Restoring punctuation and
  capitalization in transcribed speech]], In , IEEE International Conference on
  Acoustics, Speech, and Signal Processing (ICASSP) (pp. 4741–4744) (2009).
  (cite:gravano2009restoring)

** 13 May, 2019

- Ghahramani, Z., [[https://www.inf.ed.ac.uk/teaching/courses/pmr/docs/ul.pdf][Unsupervised learning]], In , Summer School on Machine Learning
  (pp. 72–112) (2003). (cite:ghahramani2003unsupervised)

- Wu, Y., Schuster, M., Chen, Z., Le, Q. V., Norouzi, M., Macherey, W., Krikun,
  M., …, [[https://arxiv.org/abs/1609.08144][Google's neural machine translation system: bridging the gap between
  human and machine translation]], arXiv preprint arXiv:1609.08144, (), (2016).
  (cite:wu2016google)

- Sculley, D., Holt, G., Golovin, D., Davydov, E., Phillips, T., Ebner, D.,
  Chaudhary, V., …, [[https://papers.nips.cc/paper/5656-hidden-technical-debt-in-machine-learning-systems][Hidden technical debt in machine learning systems]], In ,
  Advances in neural information processing systems (pp. 2503–2511) (2015).
  (cite:sculley2015hidden)

- Hundman, K., Constantinou, V., Laporte, C., Colwell, I., & Soderstrom, T.,
  [[https://arxiv.org/abs/1802.04431][Detecting spacecraft anomalies using lstms and nonparametric dynamic
  thresholding]], In , Proceedings of the 24th ACM SIGKDD International Conference
  on Knowledge Discovery \& Data Mining (pp. 387–395) (2018).
  (cite:hundman2018detecting)
